# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft_server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11raft_server.proto\"[\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateID\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\".\n\tVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\" \n\tHeartbeat\x12\x13\n\x0b\x63\x61ndidateID\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2^\n\nRaftServer\x12)\n\x0bRequestVote\x12\x0c.VoteRequest\x1a\n.VoteReply\"\x00\x12%\n\rSendHeartbeat\x12\n.Heartbeat\x1a\x06.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOTEREQUEST._serialized_start=21
  _VOTEREQUEST._serialized_end=112
  _VOTEREPLY._serialized_start=114
  _VOTEREPLY._serialized_end=160
  _HEARTBEAT._serialized_start=162
  _HEARTBEAT._serialized_end=194
  _EMPTY._serialized_start=196
  _EMPTY._serialized_end=203
  _RAFTSERVER._serialized_start=205
  _RAFTSERVER._serialized_end=299
# @@protoc_insertion_point(module_scope)
