# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\thellowrld\"\'\n\x0bVoteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\"J\n\tVoteReply\x12\x18\n\x0breturn_term\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\x42\x0e\n\x0c_return_term2K\n\nRaftServer\x12=\n\x0bRequestVote\x12\x16.hellowrld.VoteRequest\x1a\x14.hellowrld.VoteReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOTEREQUEST._serialized_start=25
  _VOTEREQUEST._serialized_end=64
  _VOTEREPLY._serialized_start=66
  _VOTEREPLY._serialized_end=140
  _RAFTSERVER._serialized_start=142
  _RAFTSERVER._serialized_end=217
# @@protoc_insertion_point(module_scope)
